apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-test-diff
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui-test
---
apiVersion: v1
kind: Secret
namespace: default
metadata:
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: t0p-Secret
